#!/bin/bash
# One-time installer: wires sync-ios.sh into a git pre-commit hook.
#
# Git hooks live in .git/hooks/ and are NOT tracked by git, so this has to be run
# once per clone. Run it from the repo root:  ./install-hook.sh

set -euo pipefail

cd "$(dirname "$0")"

HOOK=".git/hooks/pre-commit"

if [ ! -d ".git" ]; then
  echo "install-hook: not a git repository." >&2
  exit 1
fi

if [ -f "$HOOK" ]; then
  cp "$HOOK" "$HOOK.backup-$(date +%Y%m%d%H%M%S)"
  echo "install-hook: existing hook backed up (not overwritten blindly)."
fi

cat > "$HOOK" <<'EOF'
#!/bin/bash
# Auto-generated by install-hook.sh — keeps the iOS www/ copy in sync.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

[ -x ./sync-ios.sh ] || exit 0

./sync-ios.sh

# If the sync changed the iOS copy, fold it into this same commit so the two
# never drift apart in history.
if ! git diff --quiet -- pourcast-ios/www; then
  git add pourcast-ios/www
  echo "pre-commit: iOS copy re-synced and added to this commit."
fi
EOF

chmod +x "$HOOK"
chmod +x sync-ios.sh

echo "install-hook: installed $HOOK"
echo "install-hook: every commit will now keep pourcast-ios/www in sync."
